//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalificacionesExpertos
    {
        public int PeliculaID { get; set; }
        public int ExpertoID { get; set; }
        public Nullable<decimal> Calificacion { get; set; }
    
        public virtual ExpertosEnCalificaciones ExpertosEnCalificaciones { get; set; }
        public virtual Peliculas Peliculas { get; set; }
    }
}
