//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataClient
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PeliculasProgra11Entities : DbContext
    {
        public PeliculasProgra11Entities()
            : base("name=PeliculasProgra11Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActoresStaff> ActoresStaff { get; set; }
        public virtual DbSet<CalificacionesExpertos> CalificacionesExpertos { get; set; }
        public virtual DbSet<Comentarios> Comentarios { get; set; }
        public virtual DbSet<Estado> Estado { get; set; }
        public virtual DbSet<ExpertosEnCalificaciones> ExpertosEnCalificaciones { get; set; }
        public virtual DbSet<Peliculas> Peliculas { get; set; }
        public virtual DbSet<Posters> Posters { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<RolesEnPelicula> RolesEnPelicula { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    }
}
